### ISSUE TITLE
HideEvents

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#10]
## Value statement - a requirement, not a solution
As a **event participant** 
I need **a possibility to remove events from my event list** 
so that **I see only the events, I will attend** 

## Description (Text, Scribble, Wireframe, Design)

![W4 - HideEvents](https://user-images.githubusercontent.com/67911386/91591200-d51e0980-e95c-11ea-8049-105d276e86ca.png)

The Events will just be hidden, so the user can add them again to the event list

## Acceptance criteria
- [x] on click on the hide button, the event will be hidden at the main event list, after reloaded the page
- [x] the hidden events will be listed up by clicking the hidden button
- [x] if there is nothing hidden, the hidden button will not be shown
- [x]  hidden events can be shown again in the event list, by pressing the hide button again

## Tasks
- [x] create the HideEvent button
- [x] writing tests
- [x] update the storybook
- [x] integrate the button and the functionality in the app

## Size
small
