### ISSUE TITLE
CreateEventForm

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#11]
## Value statement - a requirement, not a solution
As a **event participant** 
I need **a formular** 
so that **I can add new events** 

## Description (Text, Scribble, Wireframe, Design)

![W5a - CreateEventForm](https://user-images.githubusercontent.com/67911386/91591786-c2580480-e95d-11ea-8d10-13017f912f98.png)

![W5b - CreateEventButton](https://user-images.githubusercontent.com/67911386/91591797-c71cb880-e95d-11ea-82f3-ebbb9fa4c7e3.png)

## Acceptance criteria
- [x] the form is an hidden page
- [x] the go back button will return the user to the event page
- [x] the cancel button resets the formula, but the user stays on the form page
- [x] in the drop down menu are all categories, which are available
- [x] when the ticket price input is filled out, there should be an ticket checkbox field on the info text
- [x] the form will be shown by clicking on the add event button on the main page

## Tasks
- [x] create the component CreateEventForm in storybook
- [ ] write tests
- [x] integrate the component into the app
- [x] integrate an drop down menu for the categories
- [x] write requirements for the input fields
- [x] create the form
- [x] create and go back button
- [x] when the ticket price input is filled out, there should be an ticket checkbox field on the info text
- [x] integrate the input field to link a source page
- [x] create an add event button on the main event page

## Size
large

**Comment by jennydely** [comment]
I added the Create Event formular with requirements #8

**Comment by jennydely** [comment]
The create event form and the local storage can be tested in the app here: https://event-planner.jennydely.vercel.app/

**Comment by jennydely** [comment]
I changed some requirements for the form, to fix the problems from the QA test.
Please just test the create event form:  https://event-planner-bu0eqx3dg.vercel.app/
