### ISSUE TITLE
Sorted by name or date

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#12]
## Value statement - a requirement, not a solution
As a **event participant** 
I need **an option to sort the events by name or date** 
so that **I can find a specific event easier** 

## Description (Text, Scribble, Wireframe, Design)

![W8 - AlphabeticDateFilter](https://user-images.githubusercontent.com/67911386/91599467-ad33a380-e966-11ea-8a91-3cc01a76df39.png)

## Acceptance criteria
- [x] by clicking on the Aa button, the event list will sorted by name
- [x] by clicking the date button, the event list will sorted by date

## Tasks
- [x] integrate the two buttons
- [x] integrate sort function
- [x] update storybook
- [ ] write tests

## Size
small

**Comment by jennydely** [comment]
Here you can test the sort function in the app: https://event-planner-khhzjlzig.vercel.app/

**Comment by karstenlenz** [comment]
QA results:

- I'm missing the option to choose if you want to sort descending or ascending, e.g. a-z or z-a. If you have a long list it may be useful.
- If you click "create event" and then go back to the list, either by clicking back, or creating a new event, the filter will still be active, however the dropdown at the top will show "all". The same goes for the sort function. The dropdown resets to the default value, but the list will still be sorted the same way it was before.

Apart from that it worked very well!

**Comment by jennydely** [comment]
- Added the z-a button
- fixed the dropdown problem with an reload of the page
