### ISSUE TITLE
EditEvents and Packlist

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#13]
## Value statement - a requirement, not a solution
As a **event participant** 
I need **a possibility to edit events and packlists** 
so that **I can change details and items of the events easily** 

## Description (Text, Scribble, Wireframe, Design)

![W10 - EditEventsPacklists](https://user-images.githubusercontent.com/67911386/91599653-e66c1380-e966-11ea-8715-afa1fd885649.png)

## Acceptance criteria
- [x] on click on the edit button, the edit form opens to edit the event with filled inputs
- [x] with on click on the save button, the event will be updated and saved
- [x] with click on the cancel button, the user returns to the main event page and the changes are discarded

## Tasks
- [x] add edit option
- [x] update storybook
- [x] write tests
- [x] add edit button at the event main page
- [x] add all also for the packlist

## Size
medium

**Comment by jennydely** [comment]
QA:
- it's possible edit an event
- it's possible to edit an packlist
- you need to rename the packlists, if you edit it, and another packlist with this name already exist

[App] (https://event-planner.jennydely.vercel.app/)

**Comment by carolinwagner** [comment]
QA: ✅  
everything works great!

**Comment by jennydely** [comment]
ah yes, that makes sence :)
