### ISSUE TITLE
Create packlist from template

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#14]
## Value statement - a requirement, not a solution
As a **event participant** 
I need **a possibility to use older packlists for creating a new packlist** 
so that **I don't have to write each packlist from scratch** 

## Description (Text, Scribble, Wireframe, Design)

![W12 - UseTemplatesForNewPacklist](https://user-images.githubusercontent.com/67911386/91609167-3226b900-e977-11ea-8a00-d9628ec37265.png)

## Acceptance criteria
- [x] all existing packlists should be usable as template for new packlists
- [x] the packlists can be selected via drop down menu
- [x] the items of the template will be treated like manually added items
- [x] there will be no reload by adding the template

## Tasks
- [x] create the template logic
- [x] add the button and drop down menu at the create packlist page
- [x] update the storybook
- [x] write tests

## Size
small

**Comment by jennydely** [comment]
QA:
- it's possible to create a new packlist and using an packlist template for this

[App] (https://event-planner.jennydely.vercel.app/)

**Comment by annidrumm** [comment]
QA:
. templates for a packlist work fine 👍
