### ISSUE TITLE
Add PackList

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#15]
## Value statement - a requirement, not a solution
As a **event participant** 
I need ** a packlist for each event** 
so that **I have an overview of all items I need for the event** 

## Description (Text, Scribble, Wireframe, Design)

![W6a - Packlist](https://user-images.githubusercontent.com/67911386/91611256-25a45f80-e97b-11ea-9cef-ea56fab50ce0.png)

![W6b - AddPacklistOptionToCreateEvent](https://user-images.githubusercontent.com/67911386/91611272-2dfc9a80-e97b-11ea-950b-e411cab96e23.png)

![W6c - AddPacklistButton](https://user-images.githubusercontent.com/67911386/91611285-394fc600-e97b-11ea-918e-33ce1d0cb6a8.png)

There will be 2 different packlists, which the user can choose from to add to the event.
The packlist can be added in the create event form.
The packlist will be shown, when the user clicks at the packlist button in the event text details.

## Acceptance criteria
- [x] the packlist page shows both templates, the active one should be highlighted
- [x] in the create event form will be an drop down menu, where a packlist can be selected
- [x]  it's no requirement to add a packlist
- [x] the chosen packlist will be visible as button in the event info
- [x] with click on the packlist button, the chosen packlist will be opened in a packlist page

## Tasks
- [x] create Packlist templates
- [x] create Packlist component
- [x] add Packlist button at the event info 
- [x] add Packlist drop down menu at the create event page
- [x] update storybook
- [x] write tests

## Size
small

**Comment by jennydely** [comment]
Now, you can add a packlist to your created event
the checked option for the packlist items is another user story

test the app here: https://event-planner-git-master.jennydely.vercel.app/

**Comment by karstenlenz** [comment]
QA:

I can't save the new event. When I click on the "save" button, the website input gets highlighted, but there's no error message. I entered a correct website url.

screenshot:
![image](https://user-images.githubusercontent.com/10497968/92567577-2e9c0780-f27e-11ea-864f-5f7e03e2b0fd.png)

**Comment by jennydely** [comment]
website needs to have www or http or both

**Comment by karstenlenz** [comment]
> website needs to have www or http or both

Okay, I will try again. You should add some error message.  I think it's not that user-friendly to have to type "http://:". Users usually don't type that in, because the browser will add it automatically. Also, not every website uses www. as a subdomain.

**Comment by karstenlenz** [comment]
QA results

- On Android/Chrome: In the packlist the back button is not visible without scrolling
- In the packlist you can't click on the checkbox label to select/unselect
- since every event only has one packlist (I think?) it isn't necessary to have "medieval" as a button that does nothing on click.
- if you open a packlist, refresh your tab and press the back button, you can't go back to the list.
- the checkboxes are very small (13x13px) which makes them hard to hit on a phone
- if you try to create an event with an incorrect picture URL, you can submit the form, but the event won't show up in the list. see screenshot:
![Bildschirmfoto 2020-09-09 um 10 12 37](https://user-images.githubusercontent.com/10497968/92572798-2c897700-f285-11ea-98f8-e147a8933592.png)

**Comment by jennydely** [comment]
> QA results
> 
>     * On Android/Chrome: In the packlist the back button is not visible without scrolling  <- thats already fixed in another story, maybe not updated in vercel
> 
>     * In the packlist you can't click on the checkbox label to select/unselect
> <- this is another story, as I mentioned
>     * since every event only has one packlist (I think?) it isn't necessary to have "medieval" as a button that does nothing on click.
> <- it's possible to have many different packlists, but not now. so yes the button could also be an p, but the styling of the button is the one which fits better , so I used button
>     * if you open a packlist, refresh your tab and press the back button, you can't go back to the list.
>  <- thats also fixed in the new request, dont know why vercel doesnt update this
>     * the checkboxes are very small (13x13px) which makes them hard to hit on a phone
> <- checkboxes are together with the functionality in another user story
>     * if you try to create an event with an incorrect picture URL, you can submit the form, but the event won't show up in the list. see screenshot:
>       ![Bildschirmfoto 2020-09-09 um 10 12 37](https://user-images.githubusercontent.com/10497968/92572798-2c897700-f285-11ea-98f8-e147a8933592.png)
<- thats strange, because it's working on my Andorid phone and on the pc .... maybe you have other things in the local storage so it cant beupdated?

**Comment by karstenlenz** [comment]
> <- thats strange, because it's working on my Andorid phone and on the pc .... maybe you have other things in the local storage so it cant beupdated?

I cleared my localStorage and tried again. It still won't show up in the list. But I also tried it again without the picture URL and it also won't show up. So something else is wrong. Maybe my date input is messing up the form? Did you try using the same input shown on my screenshot? Does it work for you?
(I tested in on my MacBook in Firefox)

**Comment by jennydely** [comment]
did you checked your local storage?
The event should be added to the array, but not on the list, because it's 2020 and counts..
I didn't show events before 2020, for now, there are now "old" events implemented, so events before 2020 can be added, but will not shown on the event list, because it's an eventplanner for the this year and upcoming.
I will add an filter for "old events" with an other user storie

**Comment by karstenlenz** [comment]
I checked: the entry is in localStorage. I didn't know about the year filter, so I guess then it's ok.
