### ISSUE TITLE
Create new PackList

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#16]
## Value statement - a requirement, not a solution
As a **event participant** 
I need **a possibility to create new packlists** 
so that **I can individualize my packlists depending on the event** 

## Description (Text, Scribble, Wireframe, Design)

![W7a - CreateNewPacklistForm](https://user-images.githubusercontent.com/67911386/91613176-5090b280-e97f-11ea-8f6d-d9eab22801af.png)

![W7b - AddNewPacklistAtCreateEvent](https://user-images.githubusercontent.com/67911386/91613189-55556680-e97f-11ea-9bd3-c2b44c873074.png)

![W7c - CreateNewPacklistButton](https://user-images.githubusercontent.com/67911386/91613205-5d150b00-e97f-11ea-89e7-5521d4916cb5.png)

The packlist will get a name and the user can add different tasks/items.
This tasks/items can be deleted in the create form.
The new packlist can be chosen in the create event form.
At the main event page will be the button to create a new packlist via form.

## Acceptance criteria
- [x] by clicking the create new packlist button at the main page, the packlist form will open
- [x] the packlist form has required fields, which have to be filled, before the form can be submitted
- [x] the user can create tasks/items at least 3 letters maximum of 30 letters
- [x] the tasks/items can be deleted via delete button in the form as shown in the wireframe
- [x] by pressing the reset button, the packlist will not be saved, the user will go back to the event list main page
- [x] by submit /save the form, the packlist will be saved
- [x] the new packlist will be saved and can be chosen in the drop down menu at the create event form

## Tasks
- [x] create a packlist form component
- [x] create a create new packlist button at the main event page
- [x] add the new packlist in the drop down menu of the create event form
- [x] update storybook
- [x] write tests
- [x] update styling

## Size
large

**Comment by jennydely** [comment]
updates are made
