### ISSUE TITLE
Task: datePicker component

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#19]
## Description (Text, Scribble, Wireframe, Design)

I need a date picker, so the user will send the date in the right format to the app

## Tasks
- [x] search for a datePicker
- [x] integrate the datePicker
- [x] style the datePicker
- [x] write error messages for the datePicker

## Size
small

**Comment by Lugon89** [comment]
https://blog.bitsrc.io/13-react-time-and-date-pickers-for-2020-d52d88d1ca0b

Choose wisely

**Comment by jennydely** [comment]
QA: Please test my datepicker for the form
- validation is correct (end date must be after start date)
- save into local storage is working

[App](https://event-planner-beta.vercel.app/)

**Comment by carolinwagner** [comment]
Datepicker works perfectly!
LGTM 🚀
