### ISSUE TITLE
CategoryFilter

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#2]
## Value statement - a requirement, not a solution
As a **participant** 
I need **a category filter** 
so that **I can sort my events** 

## Description (Text, Scribble, Wireframe, Design)

![W2 - CategoryFilter](https://user-images.githubusercontent.com/67911386/91590103-1a413c00-e95b-11ea-99a2-d3f3a8e62534.png)

## Acceptance criteria
- [x] each category has it's own color
- [x] there is  a button, to show all events on click him
- [x] there are different buttons for each category, on click it just show the one category
- [ ] if the category is empty, the button is not shown
- [ ] there will be at least one category button shown as placeholder, when you click him, it shows an text

## Tasks
- [x] create a new branch
- [ ] add styling for the categories
- [x] add the filter function
- [x] add the filter buttons for all and for the categories on the page
- [x] update storybook
- [x] write component tests
- [ ] write cypress tests

## Size
small

**Comment by jennydely** [comment]
I will add the styling, when the design is reviewed and write the logic for the placeholder/hide button in the next sprint
