### ISSUE TITLE
Task:  Write Packlist templates

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#23]
## Description (Text, Scribble, Wireframe, Design)

there should be 2 templates in one json file for the packlists

## Tasks
- [x] write json with objects
- [x] add 2 different packlists into the template json
- [x] the templates should be show on an own page in the app

## Size
small
