### ISSUE TITLE
EventDetails as readmore option

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#3]
## Value statement - a requirement, not a solution
As a **event-fan** 
I need **an read more info field** 
so that **I can see all details of the event, when I need them** 

## Description (Text, Scribble, Wireframe, Design)

![W3](https://user-images.githubusercontent.com/67911386/91412505-2db0b200-e84a-11ea-8674-42b05441d4da.png)

## Acceptance criteria
- [ ] Through a click on the header, it shows more text
- [ ] The detailed info text can be different for each event
- [ ] Each detailed text can be opened and closed separately
- [ ] If there is an price given in the info text, there would be an checkbox for the ticket as well

## Tasks
- [ ] create a new branch
- [ ] create info text
- [ ] create EventDetails component
- [ ] write component tests
- [ ] style the component

## Size
medium

**Comment by jennydely** [comment]
It's online here: https://event-planner-git-eventdetails.jennydely.vercel.app/

**Comment by jennydely** [comment]
adding tests as well

**Comment by jennydely** [comment]
Aktuelle App auf Vercel zum Testen: [Eventplanner](https://event-planner-git-master.jennydely.vercel.app/)
