### ISSUE TITLE
Task: Cypress tests

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#33]
Write cypress tests for all Userstories of Week 1

## Tasks
- [x] cypress test Eventlist, EventCategory, Sorting, EventDetails
- [x] cypress test Packlist
- [x] cypress test PacklistForm
- [x] cypress test EventForm

## Size
large
