### ISSUE TITLE
Task: DetailList

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#4]
## Description (Text, Scribble, Wireframe, Design)

Create a list with all event names and the details for the events.
The list contains all important details of the events, which exists already in the eventlist

## Tasks
- [x] detail recherche for all events
- [x] list up all event details
- [x] prepare all event details in an .json data form, so it can be used in the app

## Size
medium

**Comment by jennydely** [comment]
done and used for #3
