### ISSUE TITLE
Task: Create Database

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#5]
## Description (Text, Scribble, Wireframe, Design)

Create an Database to save, delete, load and update event information

## Acceptance criteria
- [ ] save events with event info
- [ ] load events with event info
- [ ] update events with event info
- [ ] delete events with event info

## Tasks
- [ ] install a database
- [ ] create a database for the event project
- [ ] fill database with default data
- [ ] integrate database to the app

## Size
medium
