### ISSUE TITLE
Task: Save Pictures

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#6]
## Description (Text, Scribble, Wireframe, Design)

Save pictures in a database, to use them every time for the event details

## Acceptance criteria
- [ ] save pictures on a database
- [ ] load pictures from the database to the event infos

## Tasks
- [ ] Post request from a picture to the database
- [ ] Get request from the event info field to the database

## Size
large
