### ISSUE TITLE
Task: Create App Design

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#7]
## Description (Text, Scribble, Wireframe, Design)

Creating a design with adobe XD, with colors, typos and components, how the app can look like when she is finished
The possible final design of the app created with adobe xd

## Tasks
- [x] create color schema
- [x] create typo schema
- [x] create some components
- [x] create an first design draft
- [x] rework of the first draft after some reviews
- [x] create the first "finaldesign"

## Size
medium

**Comment by jennydely** [comment]
Here is my preview of the first Design,
there are some bugs because of Adobe XD.... the dropdown menues should be simple dropdown menues, not flying into the app like in the example :/
[The Design](https://xd.adobe.com/view/5672f859-c942-4b94-a17c-efaf509b708f-0321/)
