### ISSUE TITLE
Task: Verify the requirements

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#8]
## Description (Text, Scribble, Wireframe, Design)

Check the requirements of each input field, which input fields are required, which are optional? How can we give a feedback as error massage to the user?
The app checks the requirements for the input fields
The app will send an error message to the user

## Tasks
- [x] write down the requirement and optional inputs
- [x]  write down the conditions in the app
- [x] write some error messages for the required inputs
- [x] test the requirements

## Size
medium
