### ISSUE TITLE
Delete EventButton

### ISSUE THREAD

**Issue by jennydely** [jennydely/Event-Planner#9]
## Value statement - a requirement, not a solution
As a **participant** 
I need **a delete button** 
so that **I can delete the whole event from the event list** 

## Description (Text, Scribble, Wireframe, Design)

![W11 - DeleteEvents](https://user-images.githubusercontent.com/67911386/91589626-5758fe80-e95a-11ea-86c9-8f017f9faace.png)

## Acceptance criteria
- [x] via click on the button, the whole event can be deleted from the event list
- [x] there should be confirm dialog, if the user really wants to delete the event or just hide it, after pressing delete again, it will be deleted everywhere
- [x]  the event is deleted

## Tasks
- [x] integrate delete function for the events into the app
- [x] create an delete button for each event in the event list
- [x] create tests
- [x] create DeleteButton in the storybook

## Size
small

**Comment by jennydely** [comment]
QA: Delete Event via Button
Testlink: https://event-planner-beta.vercel.app/
